name: Publish package to GitHub Packages

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js 18.x and set registry to GitHub Packages
        uses: actions/setup-node@v3
        with:
          node-version-file: '${{ inputs.working-directory }}/.nvmrc'
          cache: 'npm'
          cache-dependency-path: '${{ inputs.working-directory }}/package-lock.json'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm ci

      - name: Publish package to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}